create table Contrato(
IdContrato uniqueidentifier not null,
IdPlan int not null,
IdPersona uniqueidentifier not null,
IdUsuario uniqueidentifier not null,
ValorTotal decimal(18,2) not null,
Descuento int not null default(0),
ValorOriginal decimal(18,2) not null,
FechaInicio datetime not null default(getdate()),
FechaFinal datetime not null,
FechaFinalReal datetime not null,
Fecha_contrato datetime not null default(getdate()),
NumeroContrato char(6) not null unique,
IdTipoPago int not null,
IsNotValid bit not null default(0),
DescripcionIsNotValid varchar(200) default(''),
primary key (IdContrato),
foreign key (IdPlan) references Planes(IdPlanes),
foreign key (IdPersona) references Persona(IdPersona),
foreign key (IdTipoPago) references TipoPago(IdtipoPago),
foreign key (IdUsuario) references Usuario(idUsuario)
)